// Generated by @knighted/css/generate-types
// Do not edit.

export const stableSelectors = {
  'combined-types-badge': 'knighted-combined-types-badge',
  'combined-types-copy': 'knighted-combined-types-copy',
  'combined-types-footer': 'knighted-combined-types-footer',
  'combined-types-shell': 'knighted-combined-types-shell',
} as const

export type KnightedCssStableSelectors = typeof stableSelectors
export type KnightedCssStableSelectorToken = keyof typeof stableSelectors
export default stableSelectors
