// Generated by @knighted/css/generate-types (demo stub)
// Do not edit without running the selector manifest script.

export const stableSelectors = {
  'combined-types-shell': 'knighted-combined-types-shell',
  'combined-types-badge': 'knighted-combined-types-badge',
  'combined-types-copy': 'knighted-combined-types-copy',
  'combined-types-footer': 'knighted-combined-types-footer',
} as const

export type CombinedTypesStableSelectors = typeof stableSelectors
export type CombinedTypesSelectorToken = keyof typeof stableSelectors

export default stableSelectors
