// Generated by @knighted/css/generate-types
// Do not edit.

declare module './shadow-tree.js?knighted-css&combined&named-only&stable' {
  export const knightedCss: string
  export const stableSelectors: Readonly<{
    badge: 'knighted-badge'
    card: 'knighted-card'
    copy: 'knighted-copy'
    stack: 'knighted-stack'
    title: 'knighted-title'
    token: 'knighted-token'
  }>
  export const ShadowTree: typeof import('./shadow-tree.js').ShadowTree
}
