// Generated by @knighted/css/generate-types
// Do not edit.

declare module './styles.module.css?knighted-css&stable' {
  export const knightedCss: string
  export const stableSelectors: Readonly<{
    badge: 'knighted-badge'
    card: 'knighted-card'
    copy: 'knighted-copy'
    stack: 'knighted-stack'
    title: 'knighted-title'
    token: 'knighted-token'
  }>
  declare const combined: typeof import('./styles.module.css') & {
    knightedCss: string
    stableSelectors: Readonly<{
      badge: 'knighted-badge'
      card: 'knighted-card'
      copy: 'knighted-copy'
      stack: 'knighted-stack'
      title: 'knighted-title'
      token: 'knighted-token'
    }>
  }
  export default combined
}
