// Generated by @knighted/css/generate-types
// Do not edit.

export const stableSelectors = {
  badge: 'knighted-badge',
  card: 'knighted-card',
  copy: 'knighted-copy',
  stack: 'knighted-stack',
  title: 'knighted-title',
  token: 'knighted-token',
} as const

export type KnightedCssStableSelectors = typeof stableSelectors
export type KnightedCssStableSelectorToken = keyof typeof stableSelectors

export default stableSelectors
