// Generated by @knighted/css/generate-types
// Do not edit.

export const stableSelectors = {
  'fallback-card': 'knighted-fallback-card',
  'fallback-card__badge': 'knighted-fallback-card__badge',
  'fallback-card__copy': 'knighted-fallback-card__copy',
  'fallback-card__token': 'knighted-fallback-card__token',
} as const

export type KnightedCssStableSelectors = typeof stableSelectors
export type KnightedCssStableSelectorToken = keyof typeof stableSelectors

export default stableSelectors
